import React from "react";

const ExerciseDatabaseIcon = ({ width, height, className }) => {
  return (
    <svg
      id="exercise-database-icon"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      width={width}
      height={height}
      viewBox="0 0 217.64 222.64"
    >
      <title>Exercise Database Icon</title>
      <defs>
        <linearGradient
          id="exerciseBoxGradient1"
          x1="3.08"
          y1="7.06"
          x2="52.57"
          y2="48.59"
          gradientUnits="userSpaceOnUse"
        >
          <stop offset="0" stopColor="#5afdf2" />
          <stop offset=".45" stopColor="#86a7f8" />
          <stop offset=".83" stopColor="#a765fd" />
          <stop offset="1" stopColor="#b44cff" />
        </linearGradient>
        <linearGradient
          id="exerciseBoxGradient2"
          x1="84.08"
          y1="7.06"
          x2="133.57"
          y2="48.59"
          xlinkHref="#exerciseBoxGradient1"
        />
        <linearGradient
          id="exerciseBoxGradient3"
          x1="165.08"
          y1="7.06"
          x2="214.57"
          y2="48.59"
          xlinkHref="#exerciseBoxGradient1"
        />
        <linearGradient
          id="exerciseBoxGradient4"
          x1="3.08"
          y1="91.06"
          x2="52.57"
          y2="132.59"
          xlinkHref="#exerciseBoxGradient1"
        />
        <linearGradient
          id="exerciseBoxGradient5"
          x1="84.08"
          y1="91.06"
          x2="133.57"
          y2="132.59"
          xlinkHref="#exerciseBoxGradient1"
        />
        <linearGradient
          id="exerciseBoxGradient6"
          x1="165.08"
          y1="91.06"
          x2="214.57"
          y2="132.59"
          xlinkHref="#exerciseBoxGradient1"
        />
        <linearGradient
          id="exerciseBoxGradient7"
          x1="3.08"
          y1="174.06"
          x2="52.57"
          y2="215.59"
          xlinkHref="#exerciseBoxGradient1"
        />
        <linearGradient
          id="exerciseBoxGradient8"
          x1="84.08"
          y1="174.06"
          x2="133.57"
          y2="215.59"
          xlinkHref="#exerciseBoxGradient1"
        />
        <linearGradient
          id="exerciseBoxGradient9"
          x1="165.08"
          y1="174.06"
          x2="214.57"
          y2="215.59"
          xlinkHref="#exerciseBoxGradient1"
        />
      </defs>
      <rect
        id="exercise1"
        x="2.82"
        y="2.82"
        width="50"
        height="50"
        rx="14"
        fill="none"
        strokeMiterlimit="10"
        strokeWidth="5.64"
        stroke="url(#exerciseBoxGradient1)"
      />
      <rect
        id="exercise2"
        x="83.82"
        y="2.82"
        width="50"
        height="50"
        rx="14"
        fill="none"
        strokeMiterlimit="10"
        strokeWidth="5.64"
        stroke="url(#exerciseBoxGradient2)"
      />
      <rect
        id="exercise3"
        x="164.82"
        y="2.82"
        width="50"
        height="50"
        rx="14"
        fill="none"
        strokeMiterlimit="10"
        strokeWidth="5.64"
        stroke="url(#exerciseBoxGradient3)"
      />
      <rect
        id="exercise4"
        x="2.82"
        y="86.82"
        width="50"
        height="50"
        rx="14"
        fill="none"
        strokeMiterlimit="10"
        strokeWidth="5.64"
        stroke="url(#exerciseBoxGradient4)"
      />
      <rect
        id="exercise5"
        x="83.82"
        y="86.82"
        width="50"
        height="50"
        rx="14"
        fill="none"
        strokeMiterlimit="10"
        strokeWidth="5.64"
        stroke="url(#exerciseBoxGradient5)"
      />
      <rect
        id="exercise6"
        x="164.82"
        y="86.82"
        width="50"
        height="50"
        rx="14"
        fill="none"
        strokeMiterlimit="10"
        strokeWidth="5.64"
        stroke="url(#exerciseBoxGradient6)"
      />
      <rect
        id="exercise7"
        x="2.82"
        y="169.82"
        width="50"
        height="50"
        rx="14"
        fill="none"
        strokeMiterlimit="10"
        strokeWidth="5.64"
        stroke="url(#exerciseBoxGradient7)"
      />
      <rect
        id="exercise8"
        x="83.82"
        y="169.82"
        width="50"
        height="50"
        rx="14"
        fill="none"
        strokeMiterlimit="10"
        strokeWidth="5.64"
        stroke="url(#exerciseBoxGradient8)"
      />
      <rect
        id="exercise9"
        x="164.82"
        y="169.82"
        width="50"
        height="50"
        rx="14"
        fill="none"
        strokeMiterlimit="10"
        strokeWidth="5.64"
        stroke="url(#exerciseBoxGradient9)"
      />
    </svg>
  );
};

export default ExerciseDatabaseIcon;
